"""add environment_type to ConnectionProfile

Revision ID: 19799b4834ef
Revises: 002
Create Date: 2026-09-23 19:09:15.728738

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19799b4834ef'
down_revision: Union[str, Sequence[str], None] = '002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('connection_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('environment_type', sa.String(), server_default='TEST', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('connection_profiles', schema=None) as batch_op:
        batch_op.drop_column('environment_type')

    # ### end Alembic commands ###
