"""add missing indices

Revision ID: d10691d55c95
Revises: 19799b4834ef
Create Date: 2026-09-26 17:56:38.986401

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd10691d55c95'
down_revision: Union[str, Sequence[str], None] = '19799b4834ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('execution_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_execution_history_status'), ['status'], unique=False)

    with op.batch_alter_table('test_cases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_test_cases_name'), ['name'], unique=False)

    with op.batch_alter_table('test_suites', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_test_suites_name'), ['name'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_suites', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_test_suites_name'))

    with op.batch_alter_table('test_cases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_test_cases_name'))

    with op.batch_alter_table('execution_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_execution_history_status'))

    # ### end Alembic commands ###
