#!/bin/bash
echo "Ejecutando script de inicializacion de base de datos..."
sqlplus -s sys/${ORACLE_PWD}@//localhost:1521/FREEPDB1 as sysdba <<EOF
ALTER SESSION SET CONTAINER=FREEPDB1;
DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count FROM dba_users WHERE username = 'FRAMEWORK_TEST';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'CREATE USER FRAMEWORK_TEST IDENTIFIED BY "${FRAMEWORK_TEST_PASSWORD}"';
    ELSE
        EXECUTE IMMEDIATE 'ALTER USER FRAMEWORK_TEST IDENTIFIED BY "${FRAMEWORK_TEST_PASSWORD}"';
    END IF;
    
    EXECUTE IMMEDIATE 'GRANT CREATE SESSION TO FRAMEWORK_TEST';
    EXECUTE IMMEDIATE 'ALTER USER FRAMEWORK_TEST QUOTA 10M ON USERS';
END;
/

DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count FROM dba_tables WHERE owner = 'FRAMEWORK_TEST' AND table_name = 'FRAMEWORK_TEST_ITEMS';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'CREATE TABLE FRAMEWORK_TEST.FRAMEWORK_TEST_ITEMS (
            ID NUMBER PRIMARY KEY,
            NAME VARCHAR2(100) NOT NULL,
            ACTIVE NUMBER(1) DEFAULT 1 NOT NULL
        )';
    END IF;
END;
/
EXIT;
EOF
