graph TD
    subgraph Localhost / Docker Engine
        subgraph Contenedor Aplicacion
            App[FastAPI QA Framework]
            UI[Archivos Estáticos UI]
            DB_Local[(SQLite Local)]
        end
    end

    subgraph Red / Cloud
        Oracle[(Oracle Database Target)]
    end

    Client[Navegador Web] -- HTTP :8000 --> App
    App -- Lee --> UI
    App -- Lee/Escribe --> DB_Local
    App -- cx_Oracle TCP :1521 --> Oracle
