name: Security Scan and Deploy

on:
  push:
    branches:
      - main

jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Bandit (SAST Tool)
        run: pip install bandit

      - name: Run Security Scan
        run: bandit -r ./framework-pruebas-sql -f json -o bandit-report.json || true

      - name: Upload Security Report
        uses: actions/upload-artifact@v4
        with:
          name: sast-report
          path: bandit-report.json
